insert into address (address_id, street, city, province, postal_code) values (1, '7625 Dwight Plaza', 'Conception Bay South', 'Newfoundland and Labrador', 'A1W 3A3');
insert into address (address_id, street, city, province, postal_code) values (2, '84 Birchwood Way', 'Grand Bank', 'Newfoundland and Labrador', 'A0E 0A8');
insert into address (address_id, street, city, province, postal_code) values (3, '467 Declaration Way', 'Bonavista', 'Newfoundland and Labrador', 'A0C 0A6');
insert into address (address_id, street, city, province, postal_code) values (4, '35488 Arapahoe Pass', 'Burgeo', 'Newfoundland and Labrador', 'A0N 2H0');
insert into address (address_id, street, city, province, postal_code) values (5, '503 Maple Park', 'Bonavista', 'Newfoundland and Labrador', 'A0C 0A6');
insert into address (address_id, street, city, province, postal_code) values (6, '39595 Milwaukee Junction', 'Wabana', 'Newfoundland and Labrador', 'A0A 1H0');
insert into address (address_id, street, city, province, postal_code) values (7, '4 Sauthoff Crossing', 'Grand Bank', 'Newfoundland and Labrador', 'A0E 0A8');
insert into address (address_id, street, city, province, postal_code) values (8, '1249 Lakewood Point', 'Catalina', 'Newfoundland and Labrador', 'A0C 2H0');
insert into address (address_id, street, city, province, postal_code) values (9, '69 Grim Park', 'Bay Roberts', 'Newfoundland and Labrador', 'A0A 1W0');
insert into address (address_id, street, city, province, postal_code) values (10, '1 Golf View Junction', 'Carbonear', 'Newfoundland and Labrador', 'A1Y 1B1');
insert into address (address_id, street, city, province, postal_code) values (11, '66356 Nevada Alley', 'Conception Bay South', 'Newfoundland and Labrador', 'A1W 3A3');
insert into address (address_id, street, city, province, postal_code) values (12, '5192 Bobwhite Alley', 'Labrador City', 'Newfoundland and Labrador', 'A2V 0B1');
insert into address (address_id, street, city, province, postal_code) values (13, '7 Heath Road', 'Bonavista', 'Newfoundland and Labrador', 'A0C 0A6');
insert into address (address_id, street, city, province, postal_code) values (14, '7960 Esch Terrace', 'Burgeo', 'Newfoundland and Labrador', 'A0N 2H0');
insert into address (address_id, street, city, province, postal_code) values (15, '684 Northport Alley', 'Harbour Breton', 'Newfoundland and Labrador', 'M4N');
insert into address (address_id, street, city, province, postal_code) values (16, '577 Fordem Court', 'Carbonear', 'Newfoundland and Labrador', 'A1Y 1B1');
insert into address (address_id, street, city, province, postal_code) values (17, '678 Hoard Pass', 'Labrador City', 'Newfoundland and Labrador', 'A2V 0B1');
insert into address (address_id, street, city, province, postal_code) values (18, '4 Morrow Pass', 'Wabana', 'Newfoundland and Labrador', 'A0A 1H0');
insert into address (address_id, street, city, province, postal_code) values (19, '32308 Beilfuss Crossing', 'Bonavista', 'Newfoundland and Labrador', 'A0C 0A6');
insert into address (address_id, street, city, province, postal_code) values (20, '741 Norway Maple Circle', 'Labrador City', 'Newfoundland and Labrador', 'A2V 0B1');
