insert into inventory (item_id, item_name, item_stock, item_cost) values (1, 'Garbage Bag', 27, 0.99);
insert into inventory (item_id, item_name, item_stock, item_cost) values (2, 'Dog Food', 8, 4.99);
insert into inventory (item_id, item_name, item_stock, item_cost) values (3, 'Cat Food', 25, 3.99);
insert into inventory (item_id, item_name, item_stock, item_cost) values (4, 'Dog Treat', 7, 0.99);
insert into inventory (item_id, item_name, item_stock, item_cost) values (5, 'Cat Treat', 25, 0.29);
insert into inventory (item_id, item_name, item_stock, item_cost) values (6, 'Shovel', 4, 29.99);
insert into inventory (item_id, item_name, item_stock, item_cost) values (7, 'Pair of Rubber Gloves', 28, 0.29);
insert into inventory (item_id, item_name, item_stock, item_cost) values (8, 'Ton of Gravel', 5, 125.99);
insert into inventory (item_id, item_name, item_stock, item_cost) values (9, 'Ton of Top Soil', 2, 65.99);
insert into inventory (item_id, item_name, item_stock, item_cost) values (10, 'Outside - Waste Station', 6, 329.99);
insert into inventory (item_id, item_name, item_stock, item_cost) values (11, 'Rake', 5, 22.99);
insert into inventory (item_id, item_name, item_stock, item_cost) values (12, 'Sods', 15, 9.99);
insert into inventory (item_id, item_name, item_stock, item_cost) values (13, 'Doggie Bag', 124, 0.10);
insert into inventory (item_id, item_name, item_stock, item_cost) values (14, 'Inside - Waste Station', 3, 245.99);
insert into inventory (item_id, item_name, item_stock, item_cost) values (15, 'Respirators', 14, 9.99);